Turning off parallel builds on Windows. The build node is failing to compile because error C1041 (multiple CL.EXE write to the same .PDB file)
Signed-off-by: AMZN-Gene <genewalt@amazon.com>