Fixed libpng library in iOS (#169)
Libpng relies on `CMAKE_SYSTEM_PROCESSOR` variable being set to the target architecture to setup the NEON variables and include the .c neon files.

Since the iOS toolchain didn't set it, the C++ code for iOS was in a weird state that by checking the ARM macros it sets `PNG_ARM_NEON_IMPLEMENTATION` to 1 by default, so the code tries use the neon implementation but the cmake didn't include the .c neon files, leading to the linking errors seeing in the periodic builds:

````
Undefined symbols for architecture arm64:
  "_png_do_expand_palette_rgba8_neon", referenced from:
      _png_do_read_transformations in libpng16.a(pngrtran.o)
  "_png_do_expand_palette_rgb8_neon", referenced from:
      _png_do_read_transformations in libpng16.a(pngrtran.o)
  "_png_riffle_palette_neon", referenced from:
      _png_do_read_transformations in libpng16.a(pngrtran.o)
  "_png_init_filter_functions_neon", referenced from:
      _png_read_filter_row in libpng16.a(pngrutil.o)
ld: symbol(s) not found for architecture arm64
````

Setting `CMAKE_SYSTEM_PROCESSOR` to the iOS architecture in the iOS toolchain and rebuilding libpng fixes the issue.

Signed-off-by: moraaar <moraaar@amazon.com>